# Generated by Django 2.0.2 on 2018-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0010_auto_20180404_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanse',
            name='flow',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='ltrykk',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='luftfukt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='temperatur',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='vtrykk',
            field=models.FloatField(default=0),
        ),
    ]
