# Generated by Django 2.0.2 on 2018-04-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0011_auto_20180412_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanse',
            name='timestamp',
            field=models.FloatField(default=0),
        ),
    ]
