# Generated by Django 2.0.2 on 2018-04-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0012_auto_20180416_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dew_2', models.IntegerField(default=0)),
                ('dew_1', models.IntegerField(default=0)),
                ('dew', models.IntegerField(default=0)),
                ('temp', models.IntegerField(default=0)),
                ('hum', models.IntegerField(default=0)),
                ('press', models.IntegerField(default=0)),
                ('wind', models.IntegerField(default=0)),
                ('gust', models.IntegerField(default=0)),
                ('windDir', models.IntegerField(default=0)),
                ('windChill', models.IntegerField(default=0)),
                ('rain', models.IntegerField(default=0)),
                ('rainRate', models.IntegerField(default=0)),
                ('temp_1', models.IntegerField(default=0)),
                ('temp2_1', models.IntegerField(default=0)),
                ('hum_1', models.IntegerField(default=0)),
                ('temp_2', models.IntegerField(default=0)),
                ('temp2_2', models.IntegerField(default=0)),
                ('hum_2', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='LED',
        ),
    ]
