# Generated by Django 2.0.2 on 2018-04-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0013_auto_20180419_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lanse',
            old_name='ltrykk',
            new_name='lufttrykk',
        ),
        migrations.RenameField(
            model_name='lanse',
            old_name='man_steg',
            new_name='modus',
        ),
        migrations.RenameField(
            model_name='lanse',
            old_name='temperatur',
            new_name='temperatur_luft',
        ),
        migrations.RenameField(
            model_name='lanse',
            old_name='vtrykk',
            new_name='vanntrykk',
        ),
        migrations.AddField(
            model_name='lanse',
            name='temperatur_vann',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='lanse_kategori',
            field=models.CharField(default='', max_length=20),
        ),
    ]
