# Generated by Django 2.0.2 on 2018-04-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0015_auto_20180424_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
