# Generated by Django 2.0.2 on 2018-04-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0017_auto_20180424_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lansetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanseid', models.IntegerField(default=0)),
                ('lansetype', models.CharField(default='', max_length=100)),
                ('ant_steg', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Lansetyper',
            },
        ),
        migrations.DeleteModel(
            name='Lansetyper',
        ),
        migrations.AlterField(
            model_name='lanse',
            name='lanse_kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='startside.Lansetype'),
        ),
    ]
