# Generated by Django 2.0.2 on 2018-04-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0018_auto_20180424_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lansetype',
            name='lansetype',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
