# Generated by Django 2.0.2 on 2018-04-24 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0019_auto_20180424_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='langtidslagring',
            name='lanseid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='startside.Lanse'),
        ),
    ]
