# Generated by Django 2.0.2 on 2018-04-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0020_langtidslagring_lanseid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='langtidslagring',
            old_name='lanseid',
            new_name='lanse',
        ),
    ]
